title: ENGyn
description: Graphical programing interface for Autodesk Navisworks
theme: jekyll-theme-minimal
show_downloads: true
logo: /assests/img/ENGyn-300x138.png
encoding: UTF-8
lang: en
paginate: 5 # amount of posts to show
paginate_path: /page:num/
plugins:
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
