title: ENGyn
description: Graphical programing interface for Autodesk Navisworks
theme: jekyll-theme-minimal
show_downloads: true
logo: /assests/img/ENGyn-300x138.png
encoding: UTF-8
lang: en
paginate: 5 # amount of posts to show
paginate_path: /_posts/page:num
plugins:
  - jekyll-sitemap
