title: ENGyn
description: Graphical programing interface for Autodesk Navisworks
theme: jekyll-theme-minimal
show_downloads: true
logo: https://github.com/ENGworks-DEV/ENGyn/blob/master/tools/ENGyn-300x138.png
encoding: UTF-8
lang: en
plugins:
  - jekyll-sitemap
